travis:
  secure:
    BINSTAR_TOKEN: Z6xN1/HYov9KVuMli2f5mdSadcbptYJcYvx5I/eWSFFf6d7sFiho6dA96ye0ejKPkUxaIrscFaSJmqr9YsTRlb1dUPJ4fvnvHTqtrs50S9maHQFlrtrrupwQUIi6WSmyYu0I12fdPui+II9bUF3TVU8BRX9El5LKxPKQ1BrkOJvI/xeRtHynEKVoLYn6HOz/PU2ne5IreyOFoJWgJTPDNTwInQVY/f1aTL+0uRsFG6ECaYUEXf9ekq+XL2NBdiY13Y3wCmzcJvUu+FvTRKQsbE2DblNWOgZf3bMpl+BsDOBVKMdF6d1NojlnVsPExIb+4XXLkSxSer8qD1A6fvhZXrGy2AyohbCA5xtX/557YXopJDSjNJZRF8iqGXymgbdNDuCPwSztdFRvfeecnQoFuEQNoV3Rlu1bcmR3iDHLQz8WrB7P9FSiwPgL/P1n/H17n13SUKNWl4ytcVU2Ug9rJi2KSTkMvwxjE5nUyhDtFvLvBVFh64w7nz6ymIF7hTQwdChYR27WNgaQ0OVTbhkqa9pIGt56hKnumCA0S/0JNKWFhG/FrBj2IjLp9yZfOIV5i/2wy64dvjjhP6+EDniG1RFoXAzQbg8BImht5cSYSm28POA63Ngw3tX+/sqi3kfAAWexp/N0ZQeH/Yv2rqUFsfhzcfAGjB/J8GxVx5e7PVE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
